version: '3.8'

services:
  myapp:
    image: rssa_llm
    build: 
      context: .
      dockerfile: Dockerfile
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - PYTHONUNBUFFERED=1
      - INPUT_SOURCE=api # this will be changed to api in production
      - API_KEY=${API_KEY}
      - API_URL=${API_URL}
      - PORT=5050
      - LLM_PROVIDER=openai
    
    volumes:
      - ./:/app
    working_dir: /app
    command: python -u src/main.py
    ports:
      - "5050:5050"

networks:
  app_network:
    driver: bridge
