version: '3.8'

services:
  myapp:
    image: rssa_llm
    build: 
      context: .
      dockerfile: Dockerfile
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - PYTHONUNBUFFERED=1
      - INPUT_SOURCE=file # this will be changed to api in production
      - API_URL=https://api.example.com/data  # Replace with your actual API URL
      - API_KEY=your-api-key-here
    volumes:
      - ./:/app
    working_dir: /app
    command: python -u src/main.py
