general:
  llm_provider: "openai"
  port: 5050
  host: "0.0.0.0"

openai:
  model: "gpt-3.5-turbo"
  max_tokens: 4000

anthropic:
  model: "claude-3-sonnet-20240229"
  max_tokens:  4000
  temperature: 0.75

cohere:
  model: "command_r" 
